spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/cats-api
    username: admin
    password: admin
  flyway:
    enabled: true

  mvc:
    pathpattern:
      matching-strategy: ant_path_matcher